### ISSUE TITLE
"ρολόϊ" has the same stem as "ρολό" or "ρόλοι"

### ISSUE THREAD

**Issue by chief** [skroutz/greek_stemmer#1]

**Comment by astathopoulos** [comment]
This is a very difficult case. Before the stemming process the word is detoned and you cannot recognize the difference between the words "ρολοι(coming from ρολόι)" and "ρολοι(comming from ρόλοι)".

**Comment by chief** [comment]
@astathopoulos Ι know. I have some ideas to extend this stemmer's functionality and maybe resolve some ambiguities.
